export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';

export const NOTES_CREATE = 'NOTES_CREATE'
export const NOTES_LISTS = 'NOTES_LISTS'
export const NOTES_DELETE = 'NOTES_DELETE'
export const NOTES_EDIT = 'NOTES_EDIT'
export const USERS_NOTES_LISTS = 'USERS_NOTES_LISTS'
export const USER_NOTES_LISTS = 'USER_NOTES_LISTS'
export const NOTES_LIKE = 'NOTES_LIKE'
export const NOTES_UNLIKE = 'NOTES_UNLIKE'
export const NOTES_COMMENTS = 'NOTES_COMMENTS'
export const FRIENDS_NOTES = 'FRIENDS_NOTES'

export const TODOS_CREATE = 'TODOS_CREATE'
export const TODOS_LISTS = 'TODOS_LISTS'
export const TODOS_EDIT = 'TODOS_EDIT'
export const TODOS_DELETE = 'TODOS_DELETE'
export const TODOS_CHECK = 'TODOS_CHECK'

export const CREATE_INCOME = 'CREATE_INCOME'
export const LIST_INCOMES = 'LIST_INCOMES'
export const DELETE_INCOME = 'DELETE_INCOME'
export const EDIT_INCOME = 'EDIT_INCOME'

export const CREATE_EXPENSES = 'CREATE_EXPENSES'
export const LIST_EXPENSES = 'LIST_EXPENSES'
export const DELETE_EXPENSES = 'DELETE_EXPENSES'
export const EDIT_EXPENSES = 'EDIT_EXPENSES'

export const UPLOAD_AVATAR = 'UPLOAD_AVATAR'
export const GET_USER_AVATARS = 'GET_USER_AVATARS'
export const GET_ALL_AVATARS = 'GET_ALL_AVATARS'
